#zuul.routes.review-service.path=/review-service/**
#zuul.routes.customer-service.path=/customer-service/**


security:
  oauth2:
    client:
       clientId: c2c06c5b4a84a8f431ea
       clientSecret: 2de65c3759ae2a852312a53b0c0211a4a70af2c1
       accessTokenUri: https://github.com/login/oauth/access_token
       userAuthorizationUri: https://github.com/login/oauth/authorize
       clientAuthenticationScheme: form
    resource:
      user-info-uri: https://api.github.com/user
     # prefer-token-info: false

